# **Introductory Jupyter notebook**
Hi there! Welcome to this short introductory Jupyter notebook. The purpose of this notebook is to quickly introduce the way the practicals in the course will work, while also introducing you to some Numpy features. In this course, I often ask you to write functions that take specific inputs and produce specific outputs. Some of you may be used to this functional programming, while others are more familiar with scripting or coding as you go. The Introduction to Python course doesn't spend a huge amount of time on making functions (as far as I know), so this refresher might be useful. In the previous edition of the course some students thought learning ML stuff _and_ adapting to this functional style was a bit much, so this introductory notebook is to aid you **_if you need it_**. 

[Here](https://defkey.com/jupyter-notebook-shortcuts) are some Jupyter notebook keyboard shortcuts. 

In [2]:
#run this cell to set things up
import numpy as np
import seaborn as sns

## Loading in some data
Below, load in `SampleData1.csv` into the variable `my_awesome_data` using the `np.loadtxt()` function ([documentation](https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html)). Make sure to set `encoding='utf-8-sig'`. Print the data, and compute the average and standard deviation of all the values. Look for the Numpy functions to use using your favourite search engine (:

**If you have never worked with Numpy at all:** please read [this](https://numpy.org/doc/stable/user/absolute_beginners.html). 

In [7]:
#your answer here

#answer

my_awesome_data = np.loadtxt("SampleData1.csv", delimiter=',', encoding='utf-8-sig')
print(my_awesome_data)
print(np.std(my_awesome_data))
print(np.average(my_awesome_data))

[[ 12.    55.     6.  ]
 [  2.95  88.    12.  ]
 [180.     4.     3.  ]]
56.65660259214234
40.327777777777776


## Working along the axes
Okay great. You get only one value out for the average and standard deviation. That's because the default behaviour flattens the array. Maybe you want the average per row or per column. And what does flattening mean? Let's investigate.   
Below:
* print `my_awesome_data.shape`
* print `my_awesome_data.flatten()` and `my_awesome_data.flatten().shape`
* print `np.array([my_awesome_data.flatten(), np.newaxis]).shape`
* print `my_awesome_data.flatten()[:, np.newaxis]` and try to figure out what is going on by a) changing around the : and np.newaxis and b) printing the shape of the resulting array.
* Calculate the average and standard deviation over the rows of `my_awesome_data` by looking at the `axis` argument of the numpy functions used to calculate them.
* Finally, use `np.reshape()` to turn the flattened array back into the correct 3 by 3 matrix of numbers. Compare what happens when you use (3,3) and (3,-1) and (-1, 3) for the shape, and explain why this happens. Documentation is [here](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)



In [73]:
#your answer here

#answer
print(my_awesome_data.shape)
print(my_awesome_data.flatten())
print(my_awesome_data.flatten().shape)
print("\n")
print(my_awesome_data.flatten()[:, np.newaxis])
print(my_awesome_data.flatten()[:, np.newaxis].shape)
print("\n")
print(my_awesome_data.flatten()[np.newaxis, :])
print(my_awesome_data.flatten()[np.newaxis, :].shape)
print("\n")
print(np.std(my_awesome_data, axis = 1))
print(np.average(my_awesome_data, axis = 1))
print("\n")
print(np.reshape(my_awesome_data.flatten(), (3,3)))
print(np.reshape(my_awesome_data.flatten(), (3,-1)))
print(np.reshape(my_awesome_data.flatten(), (-1,3)))

(3, 3)
[ 12.    55.     6.     2.95  88.    12.   180.     4.     3.  ]
(9,)


[[ 12.  ]
 [ 55.  ]
 [  6.  ]
 [  2.95]
 [ 88.  ]
 [ 12.  ]
 [180.  ]
 [  4.  ]
 [  3.  ]]
(9, 1)


[[ 12.    55.     6.     2.95  88.    12.   180.     4.     3.  ]]
(1, 9)


[21.8225164  38.13922594 83.20389948]
[24.33333333 34.31666667 62.33333333]


[[ 12.    55.     6.  ]
 [  2.95  88.    12.  ]
 [180.     4.     3.  ]]
[[ 12.    55.     6.  ]
 [  2.95  88.    12.  ]
 [180.     4.     3.  ]]
[[ 12.    55.     6.  ]
 [  2.95  88.    12.  ]
 [180.     4.     3.  ]]


## Summing that up

What you should see is that flatten makes a set of numbers into a 1D array, with dimensions (n_numbers, ). However, if we want a table, i.e. a 2D array, we can make it by adding another axis to the data. Then, for instance, the 9-number array has dimension  (1,9), for 1 row, nine numbers. Now, you could append another row below by using `np.concatenate((my_awesome_data.flatten()[np.newaxis, :], my_awesome_data.flatten()[np.newaxis, :]))`. You don't have to do too much with this information, except that you know that Numpy uses axes to determine what 'shape' numbers are in, and we might sometimes want to change the shape. Things can break down if numbers are not both in 2D arrays when you want to combine them into a bigger table, and then you need to know what might be going on, namely: mismatched shapes.

## Working with functions

The bread and butter of this course will be me asking you to write a specific function, and you thanklessly slaving away to satisfy these inane desires. Such is life. Let's practice this!

Remember, a function in Python is defined using the def keyword, along with arguments (and optionally their standard values). Below, I give an example function definition of a highly useful function. Make sure you understand what is going on.

In [91]:
def myFunc(some_number, some_other_number, a_string_for_good_measure="String theory is not about me *cries in 17 dimensions*", printit = True):
    if printit: print("Testing 1, 2, 3:")
    if not isinstance(some_number, (int, float)) or not isinstance(some_other_number, (int,float)):
        print("Error, numbers should be numbers, man.")
        return
    the_sum = some_number + some_other_number
    if printit: print(f'Sum of numbers: {the_sum}')
    if printit: print(a_string_for_good_measure.split(" "))
    return the_sum

a_sum = myFunc(12, 3)
print("\n")
a_mistake = myFunc("whoopsie", 4)
a_sum_two_electric_boogaloo = myFunc(15, 3, printit=False)
print(a_sum)
print(a_mistake)
print(a_sum_two_electric_boogaloo)


Testing 1, 2, 3:
Sum of numbers: 15
['String', 'theory', 'is', 'not', 'about', 'me', '*cries', 'in', '17', 'dimensions*']


Testing 1, 2, 3:
Error, numbers should be numbers, man.
15
None
18


## Making functions

Say I want you to make a function `giveMeMyMatrixMan()` that takes in two arguments `shape` and `method`, in that order. Shape is a tuple with 2 values (e.g. `(5, 6)`), method can be either `'zeroes'`, `'ones'`, or `'normal'`. The function should return a matrix/table of dimension shape filled with either all 0s, all 1s, or values drawn from a standard normal distribution, depending on the method argument. If the method argument is something other than the three possibilities, the function should say so and return nothing (specifically: `None`). If the method argument is not given, it should default to the normally distributed values.

How do you tackle this? Well, the easiest way is to start by just defining variables and doing the operations necessary, and only then turning it all into a function. For instance, you could define `shape = (3,4)` and `method = 'normal'`, and then write the desired behaviour using an if-statement for method and the correct Numpy function. Then you can expand this, and finally put everything into a function. As an illustration for zeroes below:

In [77]:
shape = (3,4)
method = 'zeroes'
if not isinstance(shape, tuple):
    print("Wrong argument type! shape should be a tuple with 2 values")
if not len(shape) == 2:
    print("Wrong # of dimensions! Only 2D array supported. Change the shape tuple!")
if not isinstance(method, str) or not method in ["zeroes", "ones", "normal"]:
    print("Wrong method value, should be str and one of [zeroes, ones, normal] ")
if method == "zeroes":
    result = np.zeros(shape)
print(result)
print("\n")

#if you would only want the function to do this one thing:

def giveMeMyZeroMatrixMan(shape, method='zeroes'):
    if not isinstance(shape, tuple):
        print("Wrong argument type! shape should be a tuple with 2 values")
        return
    if not len(shape) == 2:
        print("Wrong # of dimensions! Only 2D array supported. Change the shape tuple!")
        return
    if not isinstance(method, str) or not method in ["zeroes", "ones", "normal"]:
        print("Wrong method value, should be str and one of [zeroes, ones, normal]")
        return
    if method == "zeroes":
        result = np.zeros(shape)
    else:
        result = None
    return result

print(giveMeMyZeroMatrixMan((2,8)))
print("\n")
print(giveMeMyZeroMatrixMan((2,8), method = 'normal'))
print("\n")
print(giveMeMyZeroMatrixMan((2,8), method = 'DastardlyDeviouslyWrongMethodString'))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


None


wrong method value, should be str and one of [zeroes, ones, normal]
None


## Truly up to you now!

Implement the function that can also give you a matrix of values drawn from a normal distribution and a matrix of ones.

**Note:** I went a bit far in checking the arguments. More of the function consists of that than of actual function calls. During the course you won't have to be so strict, but do keep in mind the maxim 'Fail early'. Check that things are as they should be and if not make sure to fail. It will protect you from arcane errors down the line!

In [53]:
#answer
def giveMeMyMatrixMan(shape, method='normal'):
    if not isinstance(shape, tuple):
        print("Wrong argument type! shape should be a tuple with 2 values")
        return
    if not len(shape) == 2:
        print("Wrong # of dimensions! Only 2D array supported. Change the shape tuple!")
        return
    if not isinstance(method, str) or not method in ["zeroes", "ones", "normal"]:
        print("wrong method value, should be str and one of [zeroes, ones, normal]")
        return
    if method == "zeroes":
        result = np.zeros(shape)
    if method == "ones":
        result = np.ones(shape)
    else:
        result = np.random.normal(size = shape)
    return result

print(giveMeMyMatrixMan((6,5)))

[[-0.39713649 -0.37190325  0.29314574  1.65974157  0.07761268]
 [ 0.45679147 -1.07626194  0.70287955  0.29506072  0.73362069]
 [-0.21265477  0.6250918   0.18403341 -0.07017311  0.01884878]
 [ 0.17605861  0.10675803 -0.78691116 -1.12715183  0.29759801]
 [ 0.2470295   0.604509   -0.27053491 -0.19190343 -0.11028678]
 [ 1.42279551  1.01549132  1.03847096  0.02842972 -0.27369128]]


## Sum of squares

Say you have a linear regression where you are predicting life satisfaction (which is, obviously, a measurable continuous variable from 0-100) based on the number of guitars you have stored away in your parents' attic (a continuous value if ever there was one, I have 3.79 stowed away myself). Write a function that can take in a 1D array of predicted values and a 1D array of true values, and calculate the sum of squares error term for the predictions (that is, the sum of the square of the difference between the predicted values and the true values). If you want to check whether something is an array, use `np.ndarray`. If you want to check the dimensionality of an array you can use the `.ndim` property. So:
* Make `mySSEFunction(predicted, target)` which returns a tuple of two numbers, the SSE between predicted and target, and the mean-squared error (MSE): `(SSE, MSE)`.
* Test it with the provided arrays. The result should be (111, 22.2).

In [92]:
testPred   = np.array([25, 50, 54, 80, 92])
testTarget = np.array([30, 47, 50, 74, 97])


#answer
def mySSEFunction(predicted, target):
    if not isinstance(predicted, np.ndarray) or not isinstance(target, np.ndarray):
        print("Error: predicted and target should be numpy arrays")
        return
    if not predicted.ndim == 1 or not target.ndim == 1:
        print("Error, should be 1D arrays")
        return
    SSE = np.sum(np.square(predicted-target))
    MSE = SSE/len(predicted)
    return (SSE,MSE)

print(mySSEFunction(testPred, testTarget))

(111, 22.2)


## Broadcasting

Let's look at a nice feature of Numpy: broadcasting. If you have a 3 by 4 matrix and a 3 by 1 column, you might expect that Numpy doesn't know how to multiply these. But it does, because it automatically _broadcasts_. It will assume that what you want is to multiply each of the columns in the 3 by 4 matrix with the same 3 by 1 column. See below and read up on it [here](https://www.tutorialspoint.com/numpy/numpy_broadcasting.htm).

In [79]:
mat_norm1 = np.random.normal(size = (3,4))
mat_norm2 = np.random.normal(size = (3,1))
print(mat_norm1.shape)
print(mat_norm1)
print(mat_norm2.shape)
print(mat_norm2)

print(mat_norm1 * mat_norm2)

(3, 4)
[[ 0.3871068   0.37315553 -1.14156021 -0.73131438]
 [ 0.6373373  -2.42829383 -1.42312269  0.4564624 ]
 [ 2.10510497 -0.13552691 -0.59936639 -0.10755576]]
(3, 1)
[[-0.34656863]
 [-1.50159416]
 [ 1.39565735]]
[[-0.13415907 -0.129324    0.39562896  0.25345062]
 [-0.95702196  3.64631183  2.13695271 -0.68542127]
 [ 2.93800522 -0.18914913 -0.8365101  -0.15011099]]


## Find the coordinates of the maximum and minimum value in a matrix

This is a more difficult final task to see how you get on with more minimal instructions. In principle practical exercises during the course should be explained in more detail, so just try this and see how you get on. If you don't manage or need to spend a long time: just skip it! You already have some idea of what Numpy can do and that's fine as a basis. Remember to use search engines to your advantage during the course (:

Write a function `getMaxMinCoords` that returns the coordinates of the maximum and minimum element in a `numpy.ndarray` with 2 or more dimensions as a tuple of tuples. That is, if it is a 2D array, you will get something like `((coord1_max, coord2_max), (coord1_min, coord2_min))`. Here `coord1_max` would be like the row-index of the maximal number in the 2D array, and `coord2_max` the column-index. If there's no unique maximum or minimum element, _the function should fail, return `None`, and tell you so_. Be sure to search through the documentation of Numpy and Stackoverflow for this one!
Let's not make it too arduous a search: check out `np.argmax()` and the examples on its documentation page (: Good luck!

In [5]:
test_mat_one = np.random.normal(loc = 50, scale = 5, size = (5,5))
test_mat_two = np.zeros_like(test_mat_one)
test_mat_three = np.random.normal(loc = 50, scale = 5, size = (3, 3, 3)) #this is a cube of values.
test_1D_array = np.array([42, 42, 42])


# Your function here



# Tests (uncomment once your function is done)

# print(test_mat_one)
# print(getMaxMinCoords(test_mat_one))
# print("\n")
# print(test_mat_two)
# print(getMaxMinCoords(test_mat_two))
# print("\n")
# print(test_mat_three)
# print(getMaxMinCoords(test_mat_three))

#answer
def getMaxMinCoords(array):
    if not len(array.shape) >= 2:
        print("Error: only arrays with dim >1 supported. Returning None")
        return
    max_loc = np.unravel_index(np.argmax(array, axis=None), array.shape)
    min_loc = np.unravel_index(np.argmin(array, axis=None), array.shape)
    #check for duplicates
    num_min = np.sum(array == np.min(array))
    num_max = np.sum(array == np.max(array))
    if num_min > 1 or num_max > 1:
        print("Warning: no unique maximum or minimum. Returning None")
        return 
    return (max_loc, min_loc)

print(test_mat_one)
print(getMaxMinCoords(test_mat_one))
print("\n")
print(test_mat_two)
print(getMaxMinCoords(test_mat_two))
print("\n")
print(test_mat_three)
print(getMaxMinCoords(test_mat_three))
print(getMaxMinCoords(test_1D_array))

[[54.88649843 52.25406948 47.94698762 53.84091259 48.79975653]
 [42.53457131 55.59573237 50.25012984 57.69765933 51.27240737]
 [47.04626634 51.2059809  50.8184818  50.40074358 54.76826598]
 [53.62159934 41.34593975 43.81890194 51.95068754 51.32991015]
 [45.71324807 44.88329322 55.48508832 45.24026653 57.81584609]]
((4, 4), (3, 1))


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
None


[[[43.40778719 49.29817211 44.82166851]
  [50.06342411 50.6318441  51.31804581]
  [54.67416142 48.12683628 49.62750411]]

 [[56.40703201 54.04797184 52.06947554]
  [55.36075413 45.86721311 49.57673589]
  [52.27148218 55.51186593 43.23216327]]

 [[56.46975835 42.97429161 52.38738391]
  [45.0079269  50.58720171 51.20968592]
  [47.60773041 46.73488379 43.78523453]]]
((2, 0, 0), (2, 0, 1))
Error: only arrays with dim >1 supported. Returning None
None


## Final words

This was a very basic (can you feel those hydroxide ions deep inside?) introduction to the type of practicals you'll be doing during the course: using Numpy and writing functions yourself. Of course, we will be applying that to ML problems instead of random Numpy functionality. To get a bit of an overview of ML before we get started, I highly recommend scanning [this](https://www.nature.com/articles/s41580-021-00407-0). If that doesn't work, try [this](https://rdcu.be/c6jAm). If that doesn't work you have been blessed by whatever deity you'd prefer and can skip this completely. You can skip this completely anyway since it's an optional thing to read before the course starts, but that'll be our secret. 